version: '3'

services:
  consul:
    privileged: true
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1 -config-file=/consul/config/config.json
    image: consul:latest
    container_name: consul
    restart: always
    volumes:
      - consul-data:/consul/data
      - ./consul/config.json:/consul/config/config.json
    environment: 
      - CONSUL_ALLOW_PRIVILEGED_PORTS=
      - VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - "8300:8300"
      - "8500:8500"
      - "8600:8600/udp"
    networks: 
      - config-network

  vault:
    image: vault
    restart: always
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - vault-data:/mnt/vault
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_LOCAL_CONFIG={"backend":{"consul":{"address":"consul:8500","advertise_addr":"http://localhost", "path":"vault/", "scheme":"http"}},"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":1}}}
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server
    networks: 
      - config-network
    depends_on: 
      - consul

networks: 
  config-network:
    driver: bridge

volumes:
  consul-data:
  vault-data:
